Safer use of hasOwnProperty - Fixes an error I get when GraphQL JS passes a prototypeless object into the resolver
```
ReferenceError: maybeRef is not defined
    at eval (eval at <anonymous> (/Users/mattalexander/Projects/edge-sites-schema/tests/regression.test.js:67:7), <anonymous>:1:38)
    at forEach (/Users/mattalexander/Projects/edge-sites-schema/tests/regression.test.js:67:7)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/mattalexander/Projects/edge-sites-schema/tests/regression.test.js:65:17)
```